sudo: required
services:
  - docker

before_install:
  - docker build -t yoshmatsumoto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yoshmatsumoto/react-test npm test

after_success:
  - docker build -t yoshmatsumoto/multi-client ./client
  - docker build -t yoshmatsumoto/multi-nginx ./nginx
  - docker build -t yoshmatsumoto/multi-server ./server
  - docker build -t yoshmatsumoto/multi-worker ./worker
  # Log in to the dokcer CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them into Docker hub
  - docker push yoshmatsumoto/multi-client
  - docker push yoshmatsumoto/multi-nginx
  - docker push yoshmatsumoto/multi-server
  - docker push yoshmatsumoto/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "multi-docker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-331102144433"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
